export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
export const FETCH_RESTAURANT_BY_ID = 'FETCH_RESTAURANT_BY_ID';
export const FETCH_MENU_ITEMS_BY_ID='FETCH_MENU_ITEMS_BY_ID';
export const SIGNIN='SIGNIN';
export const SIGNUP='SIGNUP';